language: python
python: "2.7"
install: 'pip install -r test_requirements.txt'
script:
    - coverage run --source=django-trees manage.py test
    - coverage report
    - coverage report | tail -n 1 | grep 100%
    - flake8 django_trees --max-line-length=120 --max-complexity=5
