language: python
python: "2.7"
install: 'pip install -r test_requirements.txt'
script:
    - pip freeze
    - python manage.py test --with-coverage --cover-package=django_trees --cover-min-percentage=100
    - flake8 django_trees --max-line-length=120 --max-complexity=5
